sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BrLEUs8AuR7hm7UvDAF0xvgJCqCJ44HtAxXYoA356Yg00Lc2e+IyRouNBxvSasO04+ss+Q8aUTFYNBscXk0j0xtpuntfd5bcFW1rpiAo+mZOO90hEiqRI9zeIKCiGOiHBKIeuXBe6X2qvXnFig/70iDPhYTSQj5Zq048Svf++TV7sj9Bdve6bX8zFtLRtY+/AoHpqpmU1HeYzP5Wgl5v+lXwo4ENO0iwwmFf2OWAyZc8tNMnB2m5izo73wrg/Tl6AGqrDdhPbwbo0sPvSLArxixGQZXJZCt9FkkSOI6+aNpZsFSJmwOqycCNhsJGx4W3RMTWWXY6dp2Ur1ibUhI+aXOH9+YboBfBNiVUz5A7D+OaWoq/pbqEHyle+0znEGen0H/nifgOb3JNqA8nqLGyGlxmrZhyBlmjkSvElSwNn5CI4HXKxMl4cbEWvgQb4GXx6I+GaKrzKhVB+BI+oYKLP5z1VkHJJvyjF6Ewooy9l+nXPc4njtND9JKHcWibhMQI2qt9Pp6Oo2vZo5zD0Khcj7bZZViLy6AbY3xja0g+J8o9oLuN/di08FFFrjxSGth2OvumJvwcXZiIbOuE0U7hKSne0OMPSDv4dOPj8GugvldT7qrfpUvbum6LyyEO9fqONz/zw4Ol+Yj5pb9xsyPY73luuIirUAgk8BQIS3emyJM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Wonderful-Balloon-Ascents--Or-The-Conquest-of-the-Skies--13-A-History-of-Balloons-and-Balloon-V__899
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy